name: Arduino CI

on: 
  push:
    branches: 
      - master
  pull_request:
    branches: 
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: pull latest arduino tarball
      run: wget https://downloads.arduino.cc/arduino-1.8.10-linux64.tar.xz
    - name: extract files
      run: tar xvf arduino-1.8.10-linux64.tar.xz
    - name: install arduino dependencies
      run: arduino-1.8.10/install.sh
